[package]
name = "mkey_map"
version = "0.1.0"
authors = ["Kevin K. <kbknapp@gmail.com>",
            "Alena Yuryeva <nimfetrisa@gmail.com>"]

[dependencies]
clap = {path="../clap-rs"}

[dev-dependencies]
clap = {path="../clap-rs"}